### ISSUE TITLE
Moving tests to testify and testcontainers

### ISSUE THREAD

**Issue by senyast4745** [meilisearch/meilisearch-go#91] opened 2020-11-02 15:37 UTC
Translating tests to [testify](https://github.com/stretchr/testify) and [testcontainers](https://golang.testcontainers.org/).

[Testify](https://github.com/stretchr/testify) will allow you to write unit tests and is also very convenient if you need to set up an environment. This is a very good JUnit counterpart for Golang. [Testcontainers](https://golang.testcontainers.org/) will allow us to raise the container with Meilisearch in runtime and test environment, which is good news in my opinion. Together with this task, it will probably be possible to close issue #16 .

**Comment by senyast4745** [comment] 2020-11-02 19:01
@eskombro @curquiza what are you thinking about this improvement?

**Comment by eskombro** [comment] 2020-11-02 21:46
I've been checking `Testify` and it seems to add a nice functionality without adding any complexity. Also it seems to be quite active and stable, and well supported, so I think it would be a great add! 👍 

`Testcontainers`, I am not 100% sure about how intersting it would be to us, because we just need to run a simple container with the same config every time for testing. And we handle it differently when you are doing tests for Unit tests or Integration, so not quite sure about how customizable it is.

Also, a little note:

When. integrating two different libraries, it might be preferable to do it separately, in different PRs. This is for avoiding conflicts in the long term: if there is a bug, conflict, etc, and you added both things at the same time, it will be harder for everyone to find / understand where the problem is coming from and how to solve it. Also it makes it impossible to revert one change without the other. So my suggestion would be:

- Create an issue (+ PR) for Testify
- Create an issue (+ PR) for Testcontainers

In my opinion, we could give testify a `go` (hah) and discuss the necesity of Testcontainers a little bit further :)

WDYT?

**Comment by senyast4745** [comment] 2020-11-03 14:02
@eskombro Hey. About testify + testcontainers. With the help of testify.suite, it will be possible not to delete the indexes in meilisearch every time after tests, but simply to recreate the container so that we can be sure that meilisearch is empty and the tests were definitely correct

**Comment by eskombro** [comment] 2020-11-03 15:35
I think that clearly `Testify` would make way cleaner tests than what we have right now! 🎉 

Feel free to start working on it if you feel like it :)

**Comment by senyast4745** [comment] 2020-11-03 15:38
@eskombro Beautiful!! 🎉 
Can you assign this issue to me?

**Comment by eskombro** [comment] 2020-11-03 22:03
After a misclick, you are assigned @senyast4745 🎉 

Thanks!

**Comment by senyast4745** [comment] 2020-11-12 22:29
@eskombro I will deal with this problem a little later. There is a lot of work so far. Hopefully this issue can wait. Thank you for understanding)

**Comment by eskombro** [comment] 2020-11-17 00:50
Thanks @senyast4745 , no problem at all, this is not urgent, it can wait until you get some time! 👍

**Comment by alallema** [comment] 2021-06-17 13:50
I closed this issue see with @eskombro. I created this #154 issue for `Testify`.
@senyast4745 don't hesitate to reopen it!

**Closed by alallema** 2021-06-17 13:50 UTC
Labels: enhancement
