### ISSUE TITLE
do search got MeilisearchCommunicationError unable to execute request

### ISSUE THREAD

**Issue by OathMoon** [meilisearch/meilisearch-go#221] opened 2021-10-21 02:42 UTC
**Description**
I have a index with about 5000 documents, 16 fileds each document, search with this index sometimes got error response below:
MeilisearchCommunicationError unable to execute request (path "POST /indexes/messages/search" with method "Search"): write tcp4 x.x.x.x:port->x.x.x.x:7700: write: broken pipe

* MeiliSearch is running in docker with parameters: --http-addr 0.0.0.0:7700 --env development --log-level DEBUG
* docker host is a centos7 virutal machine, has cpu Intel(R) Xeon(R) CPU E5-2630 v2 @ 2.60GHz and 8GB memory
* I checked docker container logs when app got error response and there's nothing
* when I use windows 10(32GB memory) docker with wsl2 backend, I can not reproduce it.

google with write: broken pipe and found fasthttp has same [issue](https://github.com/valyala/fasthttp/issues/794), but no more detail reported in this issue

**Environment :**
- OS: [Centos7 docker]
- MeiliSearch version: [v.0.23.1]
- meilisearch-go version: [v0.16.2]

**Comment by alallema** [comment] 2021-10-21 07:36
Hi @OathMoon,
Thanks for the report, someone had already reported a problem with this #113. I thought that v0.21.0 had solved this problem. Apparently no, maybe it would be a good idea to change `fasthttp` for `net/http` if the problem comes from it.

**Comment by OathMoon** [comment] 2021-11-01 07:32
Hi @alallema I did not use curl command to check MeiliSearch instance during test case, It is running in docker and I use `docker losg -f MeiliSearch` to check container logs and there noting when problem comes.
I found someone says `fasthttp` keep-alive default timeout is 10 seconds, and MeiliSearch server timeout is 5 seconds, this may causes client connection closed by server if connection idle between 5 and 10 seconds.
`fasthttp` client's write and read is synchronous,  `net/http` client use two goroutine to read and write, this is the different may the problem comes out. I did not have time to test this these days. Many thanks.

**Comment by alallema** [comment] 2021-11-15 09:02
HI @OathMoon,
Thank you very much for all this information! I will try to dig a little when I have time

**Comment by Thearas** [comment] 2022-05-24 08:40
Hi @alallema, @OathMoon and @curquiza, I got the same issue with Meilisearch v0.27 and client v0.19. I use the following code to create the client:

```go
meilisearch.NewFastHTTPCustomClient(
    meilisearch.ClientConfig{Host: endpoint},
    &fasthttp.Client{MaxIdleConnDuration: 120 * time.Minute},
)
```

Meilisearch server closed the idle connections but client still sends request on them.
<img width="1918" alt="image" src="https://user-images.githubusercontent.com/44015907/169982461-f8ecc33c-c8e2-4f94-a4c6-d29e4341a6b0.png">

There're two problems now:

1. Clearly, the lifecycle of the connection is less than the default timeout 5s. So why Meilisearch server closed the keep-alive connection?
2. Like `net/http`, fasthttp will automatically retry when the method is one of [GET, HEAD and PUT](https://github.com/valyala/fasthttp/blob/66bc61ee646a8c1bdd7121afe1cd9c27ecc682a9/client.go#L1357), but the method on search API is POST 😂, so client will never retry and change after getting broken pipe error.

I guess this can be easily fixed by specific a [RetryIf](https://github.com/valyala/fasthttp/blob/66bc61ee646a8c1bdd7121afe1cd9c27ecc682a9/client.go#L778) that can retry on search API.

**Comment by Thearas** [comment] 2022-05-24 09:05
BTW, how to set connection timeout for Meilisearch?

**Comment by alallema** [comment] 2022-05-24 10:29
Hi @Thearas,
Thanks for all these pieces of information! There is no timeout on the Meilisearch side, the server will try to answer as long as it can.

**Comment by Thearas** [comment] 2022-05-24 10:36
> Hi @Thearas, Thanks for all these pieces of information! There is no timeout on the Meilisearch side, the server will try to answer as long as it can.

It seems that actix_web does have a [default timeout 5s](https://docs.rs/actix-web/latest/actix_web/struct.HttpServer.html#method.keep_alive) ;)
And [the picture](https://user-images.githubusercontent.com/44015907/169982461-f8ecc33c-c8e2-4f94-a4c6-d29e4341a6b0.png) I posted above proves this.

**Comment by alallema** [comment] 2022-05-24 16:02
Yes, you're right! I try and I was able to let the stream open but it closed itself after 5s.
<img width="1738" alt="Screenshot 2022-05-24 at 16 31 15" src="https://user-images.githubusercontent.com/16155041/170080506-1aed9132-f11d-44d2-8600-a9d63053ba69.png">
But even if the server closes the stream I'm able to resend a new request after, I'm not sure to understand why the `golang` client gets stuck.

**Comment by Thearas** [comment] 2022-05-31 16:17
This issue can be easily reproduced by:

```go
meili := meilisearch.NewClient(meilisearch.ClientConfig{Host: "http://localhost:7700"})

// Simulate 10 clients sending requests.
g := sync.WaitGroup{}
for i := 0; i < 10; i++ {
    g.Add(1)
    go func() {
	  defer g.Done()
  
	  _, _ = meili.Index("foo").Search("bar", &meilisearch.SearchRequest{})
	  time.Sleep(5 * time.Second)
	  _, err := meili.Index("foo").Search("bar", &meilisearch.SearchRequest{})
	  if e, ok := err.(*meilisearch.Error); ok && e.ErrCode == meilisearch.MeilisearchCommunicationError {
		  panic(e)
	  }
    }()
}
g.Wait()
```

Got error:
```txt
panic: MeilisearchCommunicationError unable to execute request (path "POST /indexes/foo/search" with method "Search"): the server closed connection before returning the first response byte. Make sure the server returns 'Connection: close' response header before closing the connection
```

Though the errors are different, the TCP stream is the same, so I assume they are the same issue ;)

<img width="1541" alt="image" src="https://user-images.githubusercontent.com/44015907/171222174-3266665c-e153-4e95-8593-aca26d818d13.png">

**Comment by Thearas** [comment] 2022-06-06 20:27
> But even if the server closes the stream I'm able to resend a new request after

You're right, maybe I encountered some conner case. I'm not sure yet.

**Comment by alallema** [comment] 2022-06-07 12:17
> You're right, maybe I encountered some conner case. I'm not sure yet.

Hi @Thearas,
Thanks for the investigation, I don't think it was a corner case this issue seems to be there for a while!

**Comment by alallema** [comment] 2022-06-07 14:21
So great! Thank you so much I will check the PR 🔥

**Closed** 2022-06-08 07:21 UTC
Labels: needs investigation
